package Apresentacao;

import DAO.ClientesDAO;
import Modelo.Clientes;
import Perspectiva.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Castelhano
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    Conexao con = new Conexao();
    ClientesDAO cliDAO = new ClientesDAO();
    Clientes c = new Clientes();

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
    }

    public void Habilitar() {

    }

    public void Desabilitar() {

    }

    public void Limpar() {
        jTnome.setText(null);
        jTendereco.setText(null);
        jTemail.setText(null);
        jTbairro.setText(null);
        jTcidade.setText(null);
        jFcpf.setText(null);
        jTcpf.setText(null);
        jFrg.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTcpf = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jBnovo = new javax.swing.JButton();
        jBcadastrar = new javax.swing.JButton();
        jBbuscarCPF = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLvazio = new javax.swing.JLabel();
        jLresult = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jTnome = new javax.swing.JTextField();
        jTendereco = new javax.swing.JTextField();
        jTemail = new javax.swing.JTextField();
        jTcidade = new javax.swing.JTextField();
        jTbairro = new javax.swing.JTextField();
        jFcpf = new javax.swing.JFormattedTextField();
        jFrg = new javax.swing.JFormattedTextField();
        jCuf = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelaCliente/Client.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(68, 66, 128, 147);

        try {
            jTcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTcpf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTcpf);
        jTcpf.setBounds(0, 244, 251, 41);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Relatorio");
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 540, 251, 44);

        jBnovo.setBackground(new java.awt.Color(0, 0, 255));
        jBnovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBnovo.setForeground(new java.awt.Color(255, 255, 255));
        jBnovo.setText("Novo");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });
        jPanel1.add(jBnovo);
        jBnovo.setBounds(0, 340, 251, 44);

        jBcadastrar.setBackground(new java.awt.Color(0, 0, 255));
        jBcadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBcadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jBcadastrar);
        jBcadastrar.setBounds(0, 390, 251, 44);

        jBbuscarCPF.setBackground(new java.awt.Color(0, 0, 255));
        jBbuscarCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBbuscarCPF.setForeground(new java.awt.Color(255, 255, 255));
        jBbuscarCPF.setText("BuscarCPF");
        jBbuscarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarCPFActionPerformed(evt);
            }
        });
        jPanel1.add(jBbuscarCPF);
        jBbuscarCPF.setBounds(0, 440, 251, 44);

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Atualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(0, 490, 251, 44);

        jLvazio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLvazio.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLvazio);
        jLvazio.setBounds(20, 210, 220, 20);

        jLresult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLresult.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLresult);
        jLresult.setBounds(20, 290, 220, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 610);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(50, 84, 680, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Home Care");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 28, 131, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Codigo :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 129, 51, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nome :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(48, 172, 42, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Endereço :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(26, 217, 64, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(51, 261, 39, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cidade :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(41, 304, 49, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Bairro :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(46, 349, 44, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("CPF :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 400, 30, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Rg :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(65, 452, 25, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("UF :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(68, 507, 22, 15);

        jTcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jTcodigo);
        jTcodigo.setBounds(119, 125, 32, 20);

        jTnome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTnome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTnome);
        jTnome.setBounds(119, 173, 233, 16);

        jTendereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTendereco.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTendereco);
        jTendereco.setBounds(119, 217, 233, 16);

        jTemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTemail);
        jTemail.setBounds(119, 261, 233, 16);

        jTcidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTcidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTcidade);
        jTcidade.setBounds(119, 304, 233, 16);

        jTbairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTbairro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTbairro);
        jTbairro.setBounds(119, 349, 233, 16);

        jFcpf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        try {
            jFcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFcpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jFcpf);
        jFcpf.setBounds(119, 400, 149, 16);

        jFrg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        try {
            jFrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-###-###/#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jFrg);
        jFrg.setBounds(119, 453, 126, 16);

        jCuf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel2.add(jCuf);
        jCuf.setBounds(119, 505, 80, 21);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelaCliente/infermeira.png"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(380, 180, 370, 420);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 0, 750, 600);

        setBounds(0, 0, 1016, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        con.conectar();
        Limpar();
        String novo = "select max(id_clientes) as id_clientes from tb_clientes id_clientes";

        try {
            int id = cliDAO.Buscar_id(novo);
            jTcodigo.setText(String.valueOf(id + 1));
            jTnome.requestFocus();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarActionPerformed
        con.conectar();
        String salvar = "insert into tb_clientes values(" + jTcodigo.getText() + ",'" + jTnome.getText() + "','" + jTendereco.getText() + "','" + jTemail.getText()
                + "','" + jTcidade.getText() + "','" + jTbairro.getText() + "','" + jFcpf.getText() + "','" + jFrg.getText() + "','" + jCuf.getSelectedItem().toString() + "');";

        try {
            cliDAO.comando(salvar);
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso");
            con.desconectar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jBcadastrarActionPerformed

    private void jBbuscarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarCPFActionPerformed
        con.conectar();
        String buscar_cpf = "select * from tb_clientes where cpf='" + jTcpf.getText() + "';";

        try {
            c = cliDAO.buscar_cpf(buscar_cpf);
            
            if (jTcpf.getText().length() == 0) {
                jLvazio.setText("Campo vazio tente novamente");
            }else if(jTcpf.getText().equals(c.getCpf())){
                jTcodigo.setText(String.valueOf(c.getId_clientes()));
                jTnome.setText(c.getNome());
                jTendereco.setText(c.getEndereco());
                jTemail.setText(c.getEmail());
                jTcidade.setText(c.getCidade());
                jTbairro.setText(c.getBairro());
                jFcpf.setText(c.getCpf());
                jFrg.setText(c.getRg());
                jCuf.setSelectedItem(c.getUf());
            }else{
                jLresult.setText("CPF nao encontrado");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jBbuscarCPFActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       con.conectar();
       String atualizar = "update tb_clientes set nome='"+jTnome.getText()+"',endereco='"+jTendereco.getText()+"',email='"+jTemail.getText()
               +"',cidade='"+jTcidade.getText()+"',bairro='"+jTbairro.getText()+"',cpf='"+jFcpf.getText()+"',rg='"+jFrg.getText()
               +"',uf='"+jCuf.getSelectedItem().toString()+"' where id_clientes='"+jTcodigo.getText()+"';";

        try {
            cliDAO.comando(atualizar);
            JOptionPane.showMessageDialog(null, "Cliente Atualizada com sucesso");
            con.desconectar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscarCPF;
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jCuf;
    private javax.swing.JFormattedTextField jFcpf;
    private javax.swing.JFormattedTextField jFrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLresult;
    private javax.swing.JLabel jLvazio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JTextField jTcidade;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JFormattedTextField jTcpf;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTendereco;
    private javax.swing.JTextField jTnome;
    // End of variables declaration//GEN-END:variables
}
