package Apresentacao;

import DAO.ClientesDAO;
import Modelo.Clientes;
import Perspectiva.Conexao;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Castelhano
 */
public class TelaTabela extends javax.swing.JInternalFrame {
    Conexao con = new Conexao();
    ClientesDAO cliDAO = new ClientesDAO();
    Clientes c = new Clientes();
    List<Clientes>lista;
    /**
     * Creates new form TelaTabela
     * @param usuario
     */
    public TelaTabela(String usuario) {
        initComponents();
        jLusuario.setText(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTnome = new javax.swing.JTextField();
        jBver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPcad = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLusuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 140, 60, 15);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(44, 92, 670, 10);

        jTnome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTnome);
        jTnome.setBounds(300, 140, 230, 15);

        jBver.setText("...");
        jPanel1.add(jBver);
        jBver.setBounds(540, 130, 45, 23);

        jPcad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jPcad);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 170, 340, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelaCliente/thinking_woman_PNG11616.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 160, 500, 400);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Usuario :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 524, 80, 17);

        jLusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLusuario.setForeground(new java.awt.Color(0, 0, 204));
        jLusuario.setText("jLabel4");
        jPanel1.add(jLusuario);
        jLusuario.setBounds(620, 520, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Home Care");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 40, 140, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 570);

        setBounds(0, 0, 766, 595);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        con.conectar();
        String pegar = "select * from tb_clientes";
        
        DefaultTableModel modelo = (DefaultTableModel)jPcad.getModel();
        
        try {
            lista = cliDAO.preencherTabela(pegar);
            for (int i = 0; i < lista.size(); i++) {
               c = lista.get(i);
               
               Object[] dados = {c.getNome()};
               
               modelo.addRow(dados);
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jPcad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTnome;
    // End of variables declaration//GEN-END:variables
}
