package Apresentacao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author Castelhano
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public boolean estaFechado(Object obj){
        JInternalFrame[] ativo = jDesktop.getAllFrames();
        boolean fechado = true;
        int i = 0;
        
        while(i < ativo.length && fechado){
            if(ativo[i] == obj){
                fechado = false;
            }
            i++;
        }
        return fechado;
    }
    /**
     * Creates new form TelaPrincipal
     * @param id
     * @param usuario
     */
    public TelaPrincipal(int id, String usuario) {
        initComponents();
        
        jLid.setText(String.valueOf(id));
        jLusuario.setText(usuario);
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLusuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLhora = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMTabela = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMusuario = new javax.swing.JMenuItem();
        jMClientes = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 23, 26, 17);

        jLid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLid.setText("jLabel2");
        jPanel1.add(jLid);
        jLid.setBounds(42, 23, 30, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Usuario :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(102, 23, 61, 17);

        jLusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLusuario.setText("jLabel4");
        jPanel1.add(jLusuario);
        jLusuario.setBounds(169, 23, 76, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Data :");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(263, 23, 41, 17);

        jLdata.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLdata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLdata.setText("jLabel6");
        jLdata.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLdata);
        jLdata.setBounds(314, 23, 120, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Hora :");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 20, 43, 17);

        jLhora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLhora.setText("jLabel8");
        jLhora.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLhora);
        jLhora.setBounds(520, 20, 113, 20);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(80, 0, 10, 60);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(240, 0, 10, 60);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(440, 0, 10, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 650, 1390, 60);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktop);
        jDesktop.setBounds(0, 0, 1410, 650);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemMenu/archive (1).png"))); // NOI18N
        jMenu1.setText("Arquivo");

        jMTabela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMTabela.setText("Tabela");
        jMTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTabelaActionPerformed(evt);
            }
        });
        jMenu1.add(jMTabela);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemMenu/cuidador.png"))); // NOI18N
        jMenu2.setText("Usuario");

        jMusuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMusuario.setText("Usuario");
        jMusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMusuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMusuario);

        jMenuBar1.add(jMenu2);

        jMClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemMenu/paciente.png"))); // NOI18N
        jMClientes.setText("Cuidador");

        jMenuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuClientes.setText("Cliente");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesActionPerformed(evt);
            }
        });
        jMClientes.add(jMenuClientes);

        jMenuBar1.add(jMClientes);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemMenu/sobre.png"))); // NOI18N
        jMenu4.setText("Sobre");
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemMenu/permissao.png"))); // NOI18N
        jMenu5.setText("Desconectar");
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemMenu/rotina.png"))); // NOI18N
        jMenu6.setText("Rotina");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1421, 782));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Date dataSistema = new Date();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
       jLdata.setText(formato.format(dataSistema));
       
       Timer timer = new Timer(1000, new Hora());
       timer.start();
    }//GEN-LAST:event_formWindowOpened

    Apresentacao.TelaCliente clientes;
    private void jMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesActionPerformed
       if(estaFechado(clientes)){
           clientes = new TelaCliente();
           jDesktop.add(clientes).setLocation(150, 30);
           clientes.show();
       }else{
           clientes.show();
           clientes.toFront();
       }
    }//GEN-LAST:event_jMenuClientesActionPerformed

    Apresentacao.TelaTabela tabela;
    private void jMTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTabelaActionPerformed
        if(estaFechado(tabela)){
           tabela = new TelaTabela(jLusuario.getText());
           jDesktop.add(tabela).setLocation(150, 30);
           tabela.show();
       }else{
           tabela.show();
           tabela.toFront();
       }
    }//GEN-LAST:event_jMTabelaActionPerformed

    Apresentacao.TelaUsuario usuario;
    private void jMusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMusuarioActionPerformed
         if(estaFechado(usuario)){
           usuario = new TelaUsuario();
           jDesktop.add(usuario).setLocation(150, 30);
           usuario.show();
       }else{
           usuario.show();
           usuario.toFront();
       }
    }//GEN-LAST:event_jMusuarioActionPerformed
        public class Hora implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            Calendar agora = Calendar.getInstance();
            jLhora.setText(String.format("%1$tH:%1$tM:%1$tS", agora));
        }
            
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLdata;
    private javax.swing.JLabel jLhora;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JMenu jMClientes;
    private javax.swing.JMenuItem jMTabela;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenuItem jMusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
